version: '3.8'

services:
  docker_registry:
    image: localhost:5000/library/registry:2
    build:
      context: build/registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./data/registry:/var/lib/registry
    networks:
      - devops_network
    healthcheck:
      test: nc -z localhost 5000 || exit 1
      interval: 2s
      timeout: 10s
      retries: 3

  docker_stack_task:
    image: localhost:5000/library/ubuntu:latest
    build:
      context: build/ubuntu
    depends_on:
      docker_registry:
        condition: service_healthy
    command: /bin/sh -c "ls -la && echo $? > /result && sleep infinity"
    networks:
      - devops_network
    healthcheck:
      test: ["CMD", "cat", "/result"]
      interval: 2s
      timeout: 10s
      retries: 3

  done:
    image: localhost:5000/library/bash:latest
    build:
      context: build/bash
    depends_on:
      docker_stack_task:
        condition: service_healthy
    command: /bin/bash -c "echo done"
    networks:
      - devops_network

networks:
  devops_network:
    driver: bridge
