services:
  docker_registry:
    image: localhost:5000/library/registry:2
    build:
      context: build/registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /registry_cache:/var/lib/registry
    healthcheck:
      test: nc -z localhost 5000 || exit 1
      interval: 2s
      timeout: 10s
      retries: 3

  checkout_source:
    entrypoint: /bin/bash
    command: /action/run.sh
    working_dir: /workspace
    volumes:
      - workspace:/workspace
      - ./task/checkout_source:/action
    image: localhost:5000/library/git:latest
    build:
      context: build/git
    depends_on:
      docker_registry:
        condition: service_healthy

  build:
    entrypoint: /bin/bash
    command: /action/run.sh
    working_dir: /workspace
    volumes:
      - workspace:/workspace
      - ./task/build:/action
    image: localhost:5000/library/ubuntu:latest
    build:
      context: build/bash
    depends_on:
      checkout_source:
        condition: service_completed_successfully

  done:
    entrypoint: /bin/bash
    command: /action/run.sh
    working_dir: /workspace
    volumes:
      - workspace:/workspace
      - ./task/done:/action
    image: localhost:5000/library/ubuntu:latest
    build:
      context: build/bash
    depends_on:
      - task1

volumes:
  workspace:
