services:
  docker_registry:
    image: localhost:5000/library/registry:2
    build:
      context: build/registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /registry_cache:/var/lib/registry
    healthcheck:
      test: nc -z localhost 5000 || exit 1
      interval: 2s
      timeout: 10s
      retries: 3

  checkout_source:
    entrypoint: /bin/bash
    command: /action/run.sh
    working_dir: /workspace
    volumes:
      - workspace:/workspace
      - ${GITHUB_WORKSPACE}:/code
      - ./task/checkout_source:/action
    image: localhost:5000/library/git:latest
    build:
      context: build/git
    depends_on:
      docker_registry:
        condition: service_healthy

  trunk_check:
    entrypoint: /bin/bash
    command: /action/run.sh
    working_dir: /workspace
    volumes:
      - workspace:/workspace
      - ./task/trunk_check:/action
    image: localhost:5000/g3rhard/docker-trunk-ubuntu:latest
    build:
      context: build/trunk
    depends_on:
      checkout_source:
        condition: service_completed_successfully

  build:
    entrypoint: /bin/bash
    command: /action/run.sh
    working_dir: /workspace
    volumes:
      - workspace:/workspace
      - ./task/build:/action
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    image: localhost:5000/library/ubuntu:latest
    build:
      context: build/bash
    depends_on:
      trunk_check:
        condition: service_completed_successfully

  trivy_scan:
    entrypoint: /bin/bash
    command: /action/run.sh
    working_dir: /workspace
    volumes:
      - workspace:/workspace
      - ./task/trivy_scan:/action
    image: localhost:5000/aquasec/trivy:latest
    build:
      context: build/trivy
    depends_on:
      trunk_check:
        condition: service_completed_successfully

  done:
    entrypoint: /bin/bash
    command: /action/run.sh
    working_dir: /workspace
    volumes:
      - workspace:/workspace
      - ./task/done:/action
    image: localhost:5000/library/ubuntu:latest
    build:
      context: build/bash
    depends_on:
      - build

volumes:
  workspace:
