name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p /registry_cache
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      # - uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker-compose logs --tail all
        if: always()
      - run: docker-compose push
      - run: docker-compose down -v
