# trunk-ignore-all(checkov/CKV2_GHA_1)
name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      # - uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker-compose build
        working-directory: ./.github/actions/
      - run: docker-compose up -d
        working-directory: ./.github/actions/
      - run: docker-compose logs --tail all
        working-directory: ./.github/actions/
        if: always()
      - run: docker-compose logs --tail all > build.log
        working-directory: ./.github/actions/
        if: always()
      - run: docker-compose push
        working-directory: ./.github/actions/
        if: always()
      - run: docker-compose down -v
        working-directory: ./.github/actions/
        if: always()
      - name: Upload build log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-log
          path: ./.github/actions/build.log
