# trunk-ignore-all(checkov/CKV2_GHA_1)
name: Docker Compose Action

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: ./start.sh
        working-directory: ./.github/actions/
      - name: Upload build log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-log
          path: ./.github/actions/build.log
