name: Docker Compose Clean

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker system prune -a -f
      - run: rm -rf ~/registry_cache/*
