# trunk-ignore-all(checkov/CKV2_GHA_1)
name: Docker Compose Clean

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v3
      - run: docker run --rm -v /registry_cache:/registry_cache ubuntu bash -c "rm -rf /registry_cache/*"
      - run: docker system prune -a -f
